### ISSUE TITLE
역사적 순간 첫번째 이슈. mysql_escape 안된 변수쓰는 쿼리문 하나 발견

### ISSUE THREAD

**Issue by co2meal** [ajouansi/LavidaOnlineJudge#1]
[이 링크](https://github.com/flrngel/LavidaOnlineJudge/blob/master/submit.php#L54)

여기서 $pid는 POST로 받는거일꺼같은데 이넘 이스케이프 안되어있다

이글 보안이슈다 보니 비밀글로 올려주고 싶지만 

_어차피 아무도 안볼꺼라 강제비밀글 ㅇㅇ_

**Comment by flrngel** [comment]
일단 $pid 같은경우는 $_POST로 받는 부분이 없어서 항상 null이에요
이게 이전 라비다에서 가져온부분중 하나인데 contest일때 pid값을 가져오는데요
지금은 가져오지 않아서..
그리고 /.htaccess 보시면 아시겟지만 php_auto_prepend라는 기능을 사용해서
모든 post get값에 addslashes( php 5.4이전에서는 magic_quotes_gpc기능과 동일)를 해주기 때문에 escape처리를 따로 해주지 않아도 되여

**Comment by co2meal** [comment]
?? 그래?? 옆에 있는 변수들은 되있깅래 처리필요한줄 알았네 ㅋㅋ ㅇㅇ 

딱 그파일 하나 구경하고 써본거였음 ㅇㅇ

**Comment by co2meal** [comment]
아하 그래서 어떤 변수는 스트립 슬래시를 쓰는군 이해했음 자세한 땡큐 ㅋㅋ
