### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by alexbagirov** [ajouansi/LavidaOnlineJudge#24]
Hello!

How can I install your online judge system?
thanks.

**Comment by flrngel** [comment]
@alexbagirov install hustoj from https://code.google.com/p/hustoj/
and then install your server Apache + Php + Mysql (APM). 
after above these, follow the installation guide in `README.md`

I'm not sure it will work, beacuse hustoj version is different with 2years ago.

**Comment by alexbagirov** [comment]
Is there and English guide?

**Comment by flrngel** [comment]
what do you mean? [README](https://github.com/flrngel/LavidaOnlineJudge/blob/master/README.md) is written in english
