### ISSUE TITLE
submit.php의 stripslashes 문제

### ISSUE THREAD

**Issue by mastojun** [ajouansi/LavidaOnlineJudge#9]
[submit.php 의 33번째줄 ](https://github.com/flrngel/LavidaOnlineJudge/blob/master/submit.php#L33) 의 stripslashes 때문에 소스코드의 모든 \ 가 사라지는 문제가 있는 데요.

lavida.us 에선 문제가 없네요.

저 코드에 대해 간단히 설명 부탁드립니다~ 
지우면 어떤 문제가 생길지 모르겠네요.

**Comment by flrngel** [comment]
라비다에서 사용중인 php 5.4부터는 magic_quotes 라는 기능이 사라져서 저희는 /magic.php 를 항상 auto_prepend(.htaccess)통해 addslashes함수를 이용하여 '를 \'로("->\", ->\, \0->\0 등) 만들고 있어요. 이거는 SQL인젝션을 방지하기 위해서 인데요, 소스코드 같은경우에는 저런 따옴표 같은 것들이 magic처리되게되면 컴파일 되지 않기 때문에 저렇게 stripslashes(addslashes반대함수)를 하게 되었습니다.

magic_quotes에 관한건 http://flx.kr/1f 를 참고하셔도 좋을 것 같습니다.

**Comment by mastojun** [comment]
감사합니다~ .
htaccess to nginx config converter가 rewrite rule만 옮겨주고 (이것도 사실 몇가지 문제가 있음) php_value는 빼먹었었네요.
